### ISSUE TITLE
Push just one template?

### ISSUE THREAD

**Issue by hurrymaplelad** [sendwithus/sendwithus_sync#3]
It'd be helpful to me to able to push just one template.  Our developer flow involves pushing a template from source control to get the first version out, before marketing folks take over and set up tests.  With 30+ templates live, this step gets a little tedious for folks pushing their first email, or who haven't pushed in a while.  I wish I could tell this script to just push that one new template.

**Comment by bvanvugt** [comment]
@hurrymaplelad this is a great idea, thanks for bringing it up and sorry for the delayed response. 

Our API totally supports this -- checkout the docs here:
[https://www.sendwithus.com/docs/api/#templates](https://www.sendwithus.com/docs/api/#templates)

If you'd like to add it to this tool, we could probably test and get it merged within a couple days! Just submit a pull request and we'll take a look.

**Comment by hurrymaplelad** [comment]
Brilliant! I'll use the API, thanks!
