### ISSUE TITLE
Submit this to PyPI

### ISSUE THREAD

**Issue by gaurav-townsqd** [sendwithus/sendwithus_sync#5]
Hi SendWithUs!

Love your service! And love this package too! Thanks for working on this 😄 

Cloning this repo isn't that bad, but it would be super useful to install it via pip instead! Can we submit this to PyPI please?

**Comment by demoore** [comment]
Thanks @gaurav-townsqd! It is on pypi, though :smile_cat: 

Try this:
`pip install sendwithus`

**Comment by ianjepperson** [comment]
The `sendwithus_sync` command line tool does not appear to be on PyPI.  It doesn't appear to be part of the library that _is_ in there.

**Comment by demoore** [comment]
My bad, I was thinking of the sendwithus client repo. As mentioned in the README this isn't a plugin we support.
