### ISSUE TITLE
Handle Template Renaming

### ISSUE THREAD

**Issue by ianjepperson** [sendwithus/sendwithus_sync#7]
There doesn't seem to be a way to indicate a renamed template.  I suggest:
 - Store the template ID in a `.swu` file in the template folder.
 - When pushing or pulling, inspect the `.swu` file to determine the folder-to-template relationship.
 - Update the folder name locally or the template name remotely with any name changes.

**Comment by demoore** [comment]
This is a great idea 😸 but this package isn't something we're actively supporting at the moment. I'd love to see a pull request that implements this.
